name:                potential
version:             0.1.0.0
github:              "ndzik/potential"
license:             BSD3
author:              "Norbert Dzikowski"
maintainer:          "example@example.com"
copyright:           "2021 Norbert Dzikowski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/potential#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - random >= 1.2
    - bytestring

executables:
  potential-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - potential
    - vty
    - time
    - mtl

tests:
  potential-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - potential
    - array
    - hspec
    - text
    - random
    - time
